version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 8083:6379
    restart: always
    command: --requirepass qwedsazxc123
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./storage/redis_data:/data
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    env_file:
      - ./timezone.env
      - ./mysql/.env
    restart: always
    ports:
      - 12345:3306
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./microservice-sql:/microservice-sql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - "8084:5672"
      - "8085:15672"
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    volumes:
      - ./storage/rabbitmq_data:/data
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=MuggleLee
      - RABBITMQ_DEFAULT_PASS=987654321lihao
  RegisterCenter:
    image: com.hao/register-center:1.0
    ports:
      - "8086:8086"
    hostname: "RegisterCenter"
    container_name: "RegisterCenter"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
    volumes:
      - ./storage/logs:/logs/
  ConfigCenter:
    image: com.hao/config-center:1.0
    ports:
      - "8081:8081"
    hostname: "ConfigCenter"
    container_name: "ConfigCenter"
    restart: always
    volumes:
      - ./configs:/configs/
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  ManageBackend:
    image: com.hao/manage-backend:1.0
    ports:
      - "8092:8092"
    container_name: ManageBackend
    hostname: ManageBackend
    restart: always
    volumes:
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  LogCenter:
    image: com.hao/log-center:1.0
    ports:
      - "8088:8088"
    container_name: LogCenter
    restart: always
    volumes:
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  NotificationCenter:
    image: com.hao/notification-center:1.0
    ports:
      - "8090:8090"
    container_name: NotificationCenter
    restart: always
    volumes:
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  DeviceCenter:
    image: com.hao/device-center:1.0
    ports:
      - "9010:9010"
    container_name: DeviceCenter
    restart: always
    volumes:
      - ./DeviceCenter/target/device-center.jar:/device-center.jar
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  UserCenter:
    image: com.hao/user-center:1.0
    ports:
      - "8091:8091"
    container_name: UserCenter
    restart: always
    volumes:
      - ./UserCenter/target/user-center.jar:/user-center.jar
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  OauthCenter:
    image: com.hao/oauth-center:1.0
    ports:
      - "8082:8082"
    container_name: OauthCenter
    restart: always
    volumes:
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  GatewayCenter:
    image: com.hao/gateway-center:1.0
    ports:
      - "8093:8093"
    container_name: "GatewayCenter"
    hostname: "GatewayCenter"
    restart: always
    volumes:
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  FileCenter:
    image: com.hao/file-center:1.0
    ports:
      - "8089:8089"
    container_name: FileCenter
    restart: always
    volumes:
      - ./storage/logs:/logs/
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
  MonitorCenter:
    image: com.hao/monitor-center:1.0
    ports:
      - "9001:9001"
    container_name: MonitorCenter
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m
    volumes:
      - ./storage/logs:/logs/

volumes:
    mysql-volume: {}
