logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/cloud_file?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: qwedsazxc123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: MuggleLee
    password: 987654321lihao
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://zipkin:8090
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
security:
  oauth2:
    resource:
      user-info-uri: http://GatewayCenter:8093/api-o/user-me
      prefer-token-info: false
file:
  local:
    path: /uploadPicture/Microserver-file
    prefix: /statics
    urlPrefix: http://GatewayCenter:8093/api-f${file.local.prefix}
#  aliyun:
#    endpoint: xxx
#    accessKeyId: xxx
#    accessKeySecret: xxx
#    bucketName: xxx
#    domain: https://xxx