spring:
  redis:
    host: redis
    port: 6379
    password: qwedsazxc123
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/cloud_oauth?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: qwedsazxc123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: MuggleLee
    password: 987654321lihao
    virtual-host: /
  mvc:
    servlet:
      load-on-startup: 1
  zipkin:
    base-url: http://zipkin:8090
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1
access_token:
  store-jwt: false
  jwt-signing-key: MuggleLee=$==+_+%0%:)(:)
  add-userinfo: false
logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
ribbon:
  eager-load:
    enabled: true
    clients: UserCenter
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
