logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.104.181:12345/cloud_backend?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3306/cloud_backend?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: 47.107.104.181
    port: 8084
    username: guest
    password: 123456
    virtual-host: /
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: 18320628585@163.com
    password: QWEDSAZXC369
    protocol: smtp
    test-connection: false
#      properties:
#        mail.smtp.auth: true
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#    sender:
#      type: web
mybatis:
  type-aliases-package: com.hao.managebackend.Model,com.hao.commonmodel.Mail
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
#      user-info-uri: http://47.107.104.181:8093/api-o/user-me
      user-info-uri: http://127.0.0.1:8093/api-o/user-me
      prefer-token-info: false