logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  redis:
    host: mugglelee.top
    port: 8083
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mugglelee.top:12345/cloud_notification?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: mugglelee.top
    port: 8084
    username: guest
    password: 123456
    virtual-host: /
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://mugglelee.top:8090
    enabled: true
    sender:
      type: web
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
security:
  oauth2:
    resource:
      user-info-uri: http://mugglelee.top:8093/api-o/user-me
      prefer-token-info: false
aliyun:
  accessKeyId: LTAI4FeQVk2JCjverJCnBDCS
  accessKeySecret: 
  sign:
    name1: MuggleLee
  template:
    code1: SMS_172883578
sms:
  expire-minute: 15
  day-count: 30
